baseurl = "/"
title = "Bits & Thoughts"
author = "Hamdi Ahmed"
canonifyurls = true
paginate = 3
theme = "hugo-theme-novela"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    brand = "Home"
    description = "aether Hugo theme for blogs"
    bgimg = "/images/background.png"
    
