baseurl = "/"
languageCode = "en-us"
title = "Natrium Theme"
theme = "story"
preserveTaxonomyNames = true
rssLimit = 10
paginate = 10
pygmentsCodefences = true
pygmentsStyle = "native"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


[permalinks]
    post = "/:slug/"
    page = "/:slug/"
    
[[menu.main]]
    name = "Home"
    url = "/post/"
    weight = -110

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = -110

[params]
    classes = ["feature-[no]highlight"]
    
    
    description = ""

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
