baseurl = "/"
title = "Hamdi Ahmed Blog"
author = "Hamdi Ahmed"
canonifyurls = true
paginate = 3
theme = "aether"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    brand = "Home"
    description = "aether Hugo theme for blogs"
    bgimg = "/images/background.png"
    
