baseurl = "/"
title = "Hugo Themes - aether"
author = "Joe Hutchinson"
canonifyurls = true
paginate = 3
theme = "aether"

[params]
    brand = "aether"
    description = "aether Hugo theme for blogs"
    bgimg = "img/ignasi_pattern_s.png"
    
# Set to true to disable code folding
   disable_codefolding = false
   # Set to "hide" or "show" all codes by default
   codefolding_show = "hide"
   # Code blocks to apply code folding
   codeblocks = ["pre.sourceCode", "pre.r", "pre.python", "pre.bash", "pre.sql", "pre.cpp", "pre.stan", "pre.js", "pre.css", "pre.html", "pre.yaml"]    
