---
title: "Buybacks & Investment"
author: "Hamdi Ahmed"
date: '2018-08-12'
slug: buybacks-investment
categories: []
tags: []
---

Tax cuts have led to a surge in buybacks and a fall in tax revenues from corporations.




``` {r include = FALSE, message = FALSE, echo = FALSE}
library(dplyr)
library(plotly)
library(tidyverse)
library(readxl)
library(lubridate)

plot <- read_xls("buyback.xls")

plot$observation_date <- as.Date(plot$observation_date)

accumulate_by <- function(dat, var) {
  var <- lazyeval::f_eval(var, dat)
  lvls <- plotly:::getLevels(var)
  dats <- lapply(seq_along(lvls), function(x) {
    cbind(dat[var %in% lvls[seq(1, x)], ], frame = lvls[[x]])
  })
  dplyr::bind_rows(dats)
}

f <- plot %>%
  accumulate_by(~observation_date)


d <- ggplot(f, aes(observation_date, frame = frame)) +
  geom_line(aes(y = buybacks, colour = "buybacks"), size = 1) + 
  geom_line(aes(y = corporate_tax_income, colour = "corporate_tax_income"), size = 1) +
  geom_vline(xintercept = as.numeric(plot$observation_date[20]), linetype = "dashed", ) +
  annotate("text", label = "Tax Cut Annouced", x = plot$observation_date[17], y = -45, color = "black") +
  labs(y = "Percentage change", x = "Date") +
  theme(legend.title = element_blank())
  
```

``` {r include = FALSE, message = FALSE, echo = FALSE}
p <- ggplotly(d, width = 800) %>%
  layout(legend=list(y=0.8, yanchor="top")) %>% 
  add_annotations( text="Colour", xref="paper", yref="paper",
                  x=1.02, xanchor="left",
                  y=0.8, yanchor="bottom",    # Same y as legend below
                  legendtitle=TRUE, showarrow=FALSE ) %>%
   animation_opts(
    frame = 125,
    easing = "linear",
    transition = 0, 
    redraw = FALSE
  ) %>% 
  animation_slider(
    currentvalue = list(
      prefix = "Date"
    )
  )


```

```{r echo = FALSE, message = FALSE, warning = FALSE}

p

```



Corporate tax cuts are supposed to lead to higher business [investment](https://www.bloomberg.com/view/articles/2017-11-17/yes-a-corporate-tax-cut-would-increase-investment) but instead there’s claims that companies are foregoing investment and using the extra cash to buyback their [shares](http://theweek.com/articles/787966/ban-share-buybacks?utm_source=dlvr.it&utm_medium=twitter). Indeed, growth in business investment has recently been tepid.

