name = "aether"
license = "MIT"
licenselink = "https://github.com/josephhutch/aether/blob/master/LICENSE.md"
description = "aether is a blog theme that emphasizes motion, material, and depth as design elements to highlight the content of your site"
homepage = "https://github.com/josephhutch/aether"
tags = ["Blog", "Personal", "Responsive", "Minimal", "Simple", "Clean", "Modern", "Technical", "Syntax highlighting", "Google analytics", "Disqus", "Material Design"]
features = ["Responsive", "Highlight.js", "KaTeX", "Google analytics", "Disqus"]
min_version = "0.41"

[author]
name = "Joe Hutchinson"
homepage = "https://www.joehutch.com"

# Set to true to disable code folding
    disable_codefolding = false
# Set to "hide" or "show" all codes by default
    codefolding_show = "hide"